# Generated by Django 3.1.5 on 2021-01-28 19:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import juris.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Cadastre uma empresa (e.g. Uber).', max_length=200, validators=[django.core.validators.MinLengthValidator(4, 'O nome da empresa deve ser maior que 4 caracteres.')])),
                ('cnpj', models.IntegerField(unique=True)),
                ('ano_rfb', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TermoBusca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Cadastre os termos buscados nas bases de dados', max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(4, 'O campo do tribunal deve possuir mais que 4 caracteres.')])),
            ],
        ),
        migrations.CreateModel(
            name='TipoDecisao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProcesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tribunal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Cadastre os Tribunais do Trabalho, Tribunal Superior do Trabalho, entre outros (e.g. TRT3)', max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(4, 'O campo do tribunal deve possuir mais que 4 caracteres.')])),
            ],
        ),
        migrations.CreateModel(
            name='Varas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Cadastre as Varas do Trabalho ou de outros Tribunais, como os Cíveis.', max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(6, 'Este campo deve possuir mais que 6 caracteres.')])),
            ],
        ),
        migrations.CreateModel(
            name='Cadastrar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroProcesso', models.PositiveIntegerField()),
                ('valorProcesso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dataJulgamento', models.DateField()),
                ('observacao', models.CharField(blank=True, max_length=300)),
                ('site', models.URLField()),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', juris.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('acordoExtrajudicial', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='juris.resposta')),
                ('arquivo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='juris.arquivo')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='juris.estados')),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='juris.termobusca')),
                ('poloPassivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='juris.empresa')),
                ('tipoDecisao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='juris.tipodecisao')),
                ('tipoProcesso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='juris.tipoprocesso')),
                ('tribunal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juris.tribunal')),
                ('vinculoEmpregaticio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='juris.resposta')),
            ],
        ),
    ]
