# Generated by Django 3.1.5 on 2021-01-28 21:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import juris.models


class Migration(migrations.Migration):

    dependencies = [
        ('juris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroProcesso', models.PositiveIntegerField()),
                ('valorProcesso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dataJulgamento', models.DateField()),
                ('observacao', models.CharField(blank=True, max_length=300)),
                ('site', models.URLField()),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', juris.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('acordoExtrajudicial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='juris.resposta')),
                ('arquivo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='juris.arquivo')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='juris.estados')),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='juris.termobusca')),
            ],
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(help_text='O CNPJ dee conter 14 números.', max_length=14, validators=[django.core.validators.MinLengthValidator(14, 'O CNPJ deve conter 14 números')]),
        ),
        migrations.DeleteModel(
            name='Cadastrar',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='poloPassivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='juris.empresa'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='tipoDecisao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='juris.tipodecisao'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='tipoProcesso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='juris.tipoprocesso'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='tribunal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juris.tribunal'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='vinculoEmpregaticio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='juris.resposta'),
        ),
    ]
