# Generated by Django 3.1.5 on 2021-01-28 22:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juris', '0002_auto_20210128_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='O número do processo tem, geralmente, no mínimo 25 caracteres.', max_length=40, validators=[django.core.validators.MinLengthValidator(25, 'Preencha corretamente o número do Processo')])),
            ],
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='numeroProcesso',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='numero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='juris.numero'),
        ),
    ]
