# Generated by Django 3.1.5 on 2021-01-28 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juris', '0003_auto_20210128_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='acordoExtrajudicial',
        ),
    ]
