# Generated by Django 3.1.5 on 2021-01-29 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juris', '0004_remove_cadastro_acordoextrajudicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='acordoExtrajudicial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='juris.resposta'),
        ),
    ]
