# Generated by Django 3.1.5 on 2021-01-29 01:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juris', '0005_cadastro_acordoextrajudicial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='tipoProcesso',
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='acordoExtrajudicial',
            field=models.BooleanField(choices=[(None, '   '), (True, 'Sim'), (False, 'Não')], null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='numero',
            field=models.CharField(help_text='O número do processo tem, geralmente, no mínimo 25 caracteres.', max_length=40, unique=True, validators=[django.core.validators.MinLengthValidator(25, 'Preencha corretamente o número do Processo')]),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='pesquisa',
            field=models.CharField(help_text='Cadastre os termos buscados nas bases de dados', max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(4, 'O campo do tribunal deve possuir mais que 4 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='tribunal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='juris.tribunal'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='vinculoEmpregaticio',
            field=models.BooleanField(choices=[(None, '   '), (True, 'Sim'), (False, 'Não')], null=True),
        ),
    ]
