# Generated by Django 3.1.5 on 2021-01-29 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juris', '0008_auto_20210129_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='varas',
            name='trt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='juris.tribunal'),
        ),
    ]
