# Generated by Django 3.1.5 on 2021-01-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juris', '0011_auto_20210129_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='estado',
            field=models.CharField(choices=[('ACRE', 'ACRE'), ('ALAGOAS', 'ALAGOAS'), ('AMAPÁ', 'AMAPÁ'), ('AMAZONAS', 'AMAZONAS'), ('BAHIA', 'BA'), ('CEARÁ', 'CEARÁ'), ('DISTRITO FEDERAL', 'DISTRITO FEDERAL'), ('ESPIRITO SANTO', 'ESPIRITO SANTO'), ('GOIÁS', 'GOIÁS'), ('MARANHÃO', 'MARANHÃO'), ('MATO GROSSO', 'MATO GROSSO'), ('MATO GROSSO SUL', 'MATO GROSSO SUL'), ('MINAS GERAIS', 'MINAS GERAIS'), ('PARÁ', 'PARÁ'), ('PARAÍBA', 'PARAÍBA'), ('PARANÁ', 'PARANÁ'), ('PERNAMBUCO', 'PERNAMBUCO'), ('PIAUÍ', 'PIAUÍ'), ('RIO DE JANEIRO', 'RIO DE JANEIRO'), ('RIO GRANDE DO NORTE', 'RIO GRANDE DO NORTE'), ('RIO GRANDE DO SUL', 'RIO GRANDE DO SUL'), ('RONDÔNIA', 'RONDÔNIA'), ('RORAIMA', 'RORAIMA'), ('SANTA CATARINA', 'SANTA CATARINA'), ('SÂO PAULO', 'SÂO PAULO'), ('SERGIPE', 'SERGIPE'), ('TOCATINS', 'TOCATINS')], max_length=300, null=True),
        ),
    ]
