# Generated by Django 3.1.5 on 2021-01-31 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juris', '0012_auto_20210129_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='arquivo',
            field=models.FileField(null=True, upload_to='processos/arquivos/'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='acordoExtrajudicial',
            field=models.CharField(choices=[(None, None), ('Sim', 'Sim'), ('Não', 'Não')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='tipoProcesso',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Coletivo', 'Coletivo')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='vinculoEmpregaticio',
            field=models.CharField(choices=[(None, None), ('Sim', 'Sim'), ('Não', 'Não')], max_length=300, null=True),
        ),
    ]
