# Generated by Django 3.1.5 on 2021-02-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juris', '0013_auto_20210131_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='arquivo',
            field=models.FileField(null=True, upload_to='juris/arquivos/'),
        ),
    ]
