# Generated by Django 3.1.5 on 2021-02-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juris', '0015_processo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Processo',
        ),
        migrations.RemoveField(
            model_name='arquivo',
            name='upload',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='arquivo',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to='juris/arquivo/%Y/%m/%d'),
        ),
    ]
