# Generated by Django 3.1.5 on 2021-02-02 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juris', '0016_auto_20210202_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastro',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
    ]
