# Generated by Django 3.1.5 on 2021-02-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juris', '0018_jurisdicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='tribunal',
            field=models.CharField(choices=[('TRT1', '1ª Região - Rio de Janeiro/RJ'), ('TRT2', '2ª Região - São Paulo/SP'), ('TRT3', '3ª Região - Belo Horizonte/MG'), ('TRT4', '4ª Região - Porto Alegre/RS'), ('TRT5', '5ª Região - Salvador/BA'), ('TRT6', '6ª Região - Recife/PE'), ('TRT7', '7ª Região - Fortaleza/CE'), ('TRT8', '8ª Região - Belém/PA'), ('TRT9', '9ª Região - Curitiba/PR'), ('TRT10', '10ª Região - Brasília/DF - TO'), ('TRT11', '11ª Região - Manaus/AM - RR'), ('TRT12', '12ª Região - FLorianópolis/SC'), ('TRT13', '13ª Região - João Pessoa/PB'), ('TRT14', '14ª Região - Porto Velho/RO'), ('TRT15', '15ª Região - Campinas'), ('TRT16', '16ª Região - São Luís/MA'), ('TRT17', '17ª Região - Vitória/ES'), ('TRT18', '18ª Região - Goiânia/GO'), ('TRT19', '19ª Região - Maceió/AL'), ('TRT20', '20ª Região - Aracaju/SE'), ('TRT21', '21ª Região - Natal/RN'), ('TRT22', '22ª Região - Teresina/PI'), ('TRT23', '23ª Região - Cuiabá/MT'), ('TRT24', '24ª Região - Campo Grande/MS')], max_length=300),
        ),
    ]
