# Generated by Django 3.1.5 on 2021-02-02 23:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juris', '0020_auto_20210202_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='pesquisa',
            field=models.CharField(help_text='Cadastre os termos buscados nas bases de dados', max_length=200, validators=[django.core.validators.MinLengthValidator(4, 'O campo do tribunal deve possuir mais que 4 caracteres.')]),
        ),
    ]
