# Generated by Django 3.1.5 on 2021-02-03 02:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('juris', '0021_auto_20210202_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='dataJulgamento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to='juris/arquivo/%d %b %Y'),
        ),
    ]
