# Generated by Django 3.1.5 on 2021-02-04 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juris', '0022_auto_20210202_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='vara',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='juris.varas'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to='juris/arquivo/'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='estado',
            field=models.CharField(choices=[('ACRE', 'ACRE'), ('ALAGOAS', 'ALAGOAS'), ('AMAPÁ', 'AMAPÁ'), ('AMAZONAS', 'AMAZONAS'), ('BAHIA', 'BAHIA'), ('CEARÁ', 'CEARÁ'), ('DISTRITO FEDERAL', 'DISTRITO FEDERAL'), ('ESPIRITO SANTO', 'ESPIRITO SANTO'), ('GOIÁS', 'GOIÁS'), ('MARANHÃO', 'MARANHÃO'), ('MATO GROSSO', 'MATO GROSSO'), ('MATO GROSSO SUL', 'MATO GROSSO SUL'), ('MINAS GERAIS', 'MINAS GERAIS'), ('PARÁ', 'PARÁ'), ('PARAÍBA', 'PARAÍBA'), ('PARANÁ', 'PARANÁ'), ('PERNAMBUCO', 'PERNAMBUCO'), ('PIAUÍ', 'PIAUÍ'), ('RIO DE JANEIRO', 'RIO DE JANEIRO'), ('RIO GRANDE DO NORTE', 'RIO GRANDE DO NORTE'), ('RIO GRANDE DO SUL', 'RIO GRANDE DO SUL'), ('RONDÔNIA', 'RONDÔNIA'), ('RORAIMA', 'RORAIMA'), ('SANTA CATARINA', 'SANTA CATARINA'), ('SÂO PAULO', 'SÂO PAULO'), ('SERGIPE', 'SERGIPE'), ('TOCATINS', 'TOCATINS')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='tribunal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='juris.tribunal'),
        ),
    ]
