# Generated by Django 3.1.5 on 2021-02-04 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juris', '0024_auto_20210204_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varas',
            name='trt',
        ),
        migrations.AddField(
            model_name='varas',
            name='vara',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='juris.tribunal'),
        ),
    ]
