# Generated by Django 3.1.5 on 2021-02-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juris', '0027_auto_20210206_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='tribunal',
            field=models.CharField(choices=[('1ª Região - Rio de Janeiro/RJ', '1ª Região - Rio de Janeiro/RJ'), ('2ª Região - São Paulo/SP', '2ª Região - São Paulo/SP'), ('3ª Região - Belo Horizonte/MG', '3ª Região - Belo Horizonte/MG'), ('4ª Região - Porto Alegre/RS', '4ª Região - Porto Alegre/RS'), ('5ª Região - Salvador/BA', '5ª Região - Salvador/BA'), ('6ª Região - Recife/PE', '6ª Região - Recife/PE'), ('7ª Região - Fortaleza/CE', '7ª Região - Fortaleza/CE'), ('8ª Região - Belém/PA', '8ª Região - Belém/PA'), ('9ª Região - Curitiba/PR', '9ª Região - Curitiba/PR'), ('10ª Região - Brasília/DF - TO', '10ª Região - Brasília/DF - TO'), ('11ª Região - Manaus/AM - RR', '11ª Região - Manaus/AM - RR'), ('12ª Região - FLorianópolis/SC', '12ª Região - FLorianópolis/SC'), ('13ª Região - João Pessoa/PB', '13ª Região - João Pessoa/PB'), ('14ª Região - Porto Velho/RO', '14ª Região - Porto Velho/RO'), ('15ª Região - Campinas', '15ª Região - Campinas'), ('16ª Região - São Luís/MA', '16ª Região - São Luís/MA'), ('17ª Região - Vitória/ES', '17ª Região - Vitória/ES'), ('18ª Região - Goiânia/GO', '18ª Região - Goiânia/GO'), ('19ª Região - Maceió/AL', '19ª Região - Maceió/AL'), ('20ª Região - Aracaju/SE', '20ª Região - Aracaju/SE'), ('21ª Região - Natal/RN', '21ª Região - Natal/RN'), ('22ª Região - Teresina/PI', '22ª Região - Teresina/PI'), ('23ª Região - Cuiabá/MT', '23ª Região - Cuiabá/MT'), ('24ª Região - Campo Grande/MS', '24ª Região - Campo Grande/MS'), ('TST -Tribunal Superior do Trabalho', 'TST -Tribunal Superior do Trabalho')], max_length=300, null=True),
        ),
    ]
