# Generated by Django 3.1.5 on 2021-02-07 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juris', '0030_auto_20210206_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='tribunal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='juris.tribunal'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='vara',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='juris.varas'),
        ),
    ]
