# Generated by Django 3.1.5 on 2021-02-07 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juris', '0031_auto_20210207_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varas',
            name='regiao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='juris.tribunal'),
        ),
    ]
