# Generated by Django 3.1.5 on 2021-02-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juris', '0033_auto_20210207_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jurisdicao',
            old_name='vara',
            new_name='varas',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='turma',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
