# Generated by Django 3.1.5 on 2021-02-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juris', '0034_auto_20210207_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='tribunal',
            field=models.CharField(choices=[(1, 'TRT1'), (2, 'TRT2'), (3, 'TRT3'), (4, 'TRT4'), (5, 'TRT5'), (6, 'TRT6'), (7, 'TRT7'), (8, 'TRT8'), (9, 'TRT9'), (10, 'TRT10'), (11, 'TRT11'), (12, 'TRT12'), (13, 'TRT13'), (14, 'TRT14'), (15, 'TRT15'), (16, 'TRT16'), (17, 'TRT17'), (18, 'TRT18'), (19, 'TRT19'), (20, ' TRT20'), (21, 'TRT21'), (22, 'TRT22'), (23, 'TRT23'), (24, 'TRT24'), (25, 'TST')], max_length=200, null=True),
        ),
    ]
